name: Destroy
on:
  workflow_dispatch:
jobs:
  apply:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Terraform Apply
        run: make dev-destroy token=${vault_token}
        env:
          vault_token: ${{ secrets.VAULT_TOKEN }}
